### ISSUE TITLE
Unable to cast default values to matching type

### ISSUE THREAD

**Issue by tomdottom** [liquidata-inc/dolt#529] opened 2020-04-07 20:05 UTC
I get the following error:

> query error: expecting all case branches to return values of type BIGINT, but found value "0" of type TINYINT on CASE WHEN cases.death_count THEN cases.death_count ELSE 0 END

When running the following query against the `Liquidata/corona-virus` data repo:

```sql
SELECT
  (
    CASE WHEN `death_count`
    THEN
      `death_count`
    ELse
      0
    END
  ) as `death_count`
FROM `cases`
WHERE place_id = 46
LIMIT 1;

```

I have also been unable to cast/convert the default `TINYINT` type to a `BIGINT` type as both the `CAST` and `CONVERT` functions raise sql parsing errors.

### Refs:

Example query: https://www.dolthub.com/repositories/Liquidata/corona-virus/query/master?q=SELECT%0A%20%20(%0A%20%20%20%20CASE%20WHEN%20%60death_count%60%0A%20%20%20%20THEN%0A%20%20%20%20%20%20%60death_count%60%0A%20%20%20%20ELse%0A%20%20%20%20%20%200%0A%20%20%20%20END%0A%20%20)%20as%20%60death_count%60%0AFROM%20%60cases%60%0AWHERE%20place_id%20%3D%2046%0ALIMIT%201%3B%0A

Screenshot:

![image](https://user-images.githubusercontent.com/5106166/78712970-7d1c3300-78e7-11ea-9d0a-0541628bce6e.png)

**Comment by Hydrocharged** [comment] 2020-04-07 20:23
Thank you for the bug report Tom, I'm going to look into this.

**Comment by Hydrocharged** [comment] 2020-04-08 02:16
> I have also been unable to cast/convert the default TINYINT type to a BIGINT type as both the CAST and CONVERT functions raise sql parsing errors.

Would you mind writing an example query where you're casting to these types?

**Comment by tomdottom** [comment] 2020-04-08 02:38
@Hydrocharged whilst trying to create an example for you I've spotted an error in my own query. 

The following does indeed cast as expected. 

```sql
SELECT
  (
    CASE WHEN `death_count`
    THEN
      `death_count`
    ELSE
      CAST(0 AS SIGNED)
    END
  ) as `death_count`
FROM `cases`
WHERE place_id = 46
LIMIT 1;
```

However, I am surprised that the correct type isn't implicitly created. The following two equivalent queries work without need of casting an behave as I expected the `CASE` switch to:

```sql
SELECT COALESCE(`death_count`, 0) as `death_count`
FROM `cases`
LIMIT 100;
```

and

```sql
SELECT IFNULL(`death_count`, 0) as `death_count`
FROM `cases`
LIMIT 100;
```

If this the correct and expected behaviour please close the issue with my apologies.

T

**Comment by Hydrocharged** [comment] 2020-04-08 02:49
Thank you for the responsiveness!

I'm glad the cast works as expected! We should be handling the type internally though, thus the issue is still valid. I should have a fix for this very soon!

**Comment by Hydrocharged** [comment] 2020-04-08 03:29
I've fixed the issue and merged it into the `go-mysql-server` project. I can't quite sync `dolt` with the latest changes just yet, as there are a few more changes we need to make before doing so, but it will be in by the next release.

Thanks once again for the bug report! If you find anything else, do let us know!

**Closed by Hydrocharged** 2020-04-08 03:29 UTC
Labels: bug, sql
